### ISSUE TITLE
Content(ful) webhook fails—no access to Jenkins project

### ISSUE THREAD

**Issue by dnoesgaard** [gbif/content-crawler#11]
The webhook called by Contentful when new content is published stopped working today:

![Screenshot 2019-03-11 at 14 55 40](https://user-images.githubusercontent.com/21358085/54129106-d75d7280-440d-11e9-81e4-1227fde5d85f.png)

I also get a 404 when trying to access the Jenkins project:
https://builds.gbif.org/job/run-content-crawler/

**Comment by MattBlissett** [comment]
I ugraded Jenkins (just with yum) and something has changed to do with logging in.

**Comment by dnoesgaard** [comment]
I get the same 404 error whether I'm logged in or not.

For Contentful, it's the same:

```
Response headers
{
  "date": "Mon, 11 Mar 2019 14:34:14 GMT",
  "content-type": "text/html; charset=ISO-8859-1",
  "content-length": "296",
  "cache-control": "no-cache, no-store, must-revalidate",
  "x-varnish": "7406586",
  "age": "0",
  "via": "1.1 varnish (Varnish/5.2)",
  "connection": "close"
}
Response body
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<title>Error 404 Not Found</title>
</head>
<body><h2>HTTP ERROR 404</h2>
<p>Problem accessing /content/sync. Reason:
<pre>    Not Found</pre></p><hr><i><small>Powered by Jetty://</small></i><hr/>

</body>
</html>
```

**Comment by MattBlissett** [comment]
Fixing the configuration option which was preventing the Jenkins Github plugin from being upgraded (and then upgrading the plugin) has resolved this.
