### ISSUE TITLE
semicolon not considered a delimiter

### ISSUE THREAD

**Issue by MortenHofft** [gbif/content-crawler#12]
In the ES literature index:
`country` and `countriesOfResearcher` differ in parsing. `country` should be an array as well.
```
"country": "NO;IS;DK;CA;GB;SE;US;FI;RU;ZA",
"countriesOfResearcher": [
"NO",
"SE",
"FI",
"RU",
"DK",
"ZA",
"IS",
"GB",
"CA",
"US"
],
```

**Comment by dnoesgaard** [comment]
I believe `country` is directly from Mendeley, but not "used" by the ES index. I believe `countriesOfResearcher` comes from tags...

**Comment by MortenHofft** [comment]
kk - in that case let us not fix that

**Comment by dnoesgaard** [comment]
Right. I didn't start populating this field until recently. Can't actually remember why...

**Comment by MortenHofft** [comment]
I actually mistook it for countryOfCoverage - thinking that was the "other" country. Didn't know we had 3 field for countries.

**Comment by dnoesgaard** [comment]
I know, it's a bit messy. I think all fields from Mendeley are indexed as-is, and a few more are then created in ES based on tags, etc.
