### ISSUE TITLE
Error on maven build

### ISSUE THREAD

**Issue by NullConvergence** [gbif/content-crawler#14]
Hi, I've tried to build the project, but I get the following error when running maven build: Failed to load existing service definition files: java.nio.file.NoSuchFileException: /content-crawler/target/classes/META-INF/services/org.gbif.cli.Command

Moreover, I am not sure how to configure the yml file with the app id and secret.
Can you lend me a hand?:)

Many thanks!

**Comment by timrobertson100** [comment]
Can you please share the output of `mvn --version` and what happens when you `mvn clean package`?

**Comment by NullConvergence** [comment]
Sure:
$ mvn --version
Apache Maven 3.5.2
Maven home: /usr/share/maven
Java version: 11.0.3, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.18.0-20-generic", arch: "amd64", family: "unix"

$ mvn clean package

[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.277 s
[INFO] Finished at: 2019-05-25T11:13:43+02:00
[INFO] Final Memory: 40M/174M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.2:compile (default-compile) on project content-crawler: Compilation failure
[ERROR] Failed to load existing service definition files: java.nio.file.NoSuchFileException: /home/alex/Documents/Projects/content-crawler/target/classes/META-INF/services/org.gbif.cli.Command
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException


Let me know any questions. Also, where and how should I configure the Mendeley data?

**Comment by timrobertson100** [comment]
I believe it will build with Java 8

**Comment by NullConvergence** [comment]
It does, you can close this issue.

**Comment by jiangouawu** [comment]
i have similar issue. why java 11 could not work? since we trying to upgrade to java 11 from java8. if there is any work around for java11?
