### ISSUE TITLE
link articles to programemes

### ISSUE THREAD

**Issue by MortenHofft** [gbif/content-crawler#26]
@dnoesgaard would like to link other things than news to programmes.
The model is prepared in contentful dev.

@Federico It seems the tag is only added to news. 

https://app.contentful.com/spaces/qz96qz790wh9/entries/82243 the programme has 5 related "news", 2 news and 3 articles. But only the news are searchable http://cms-search.gbif-dev.org:9200/content/_search?q=programmeTag:82243

**Comment by timrobertson100** [comment]
@dnoesgaard can you please list the content types you anticipate linking or is it only articles?

**Comment by dnoesgaard** [comment]
Just articles, thanks
