### ISSUE TITLE
Suggestion: index taxonKey tag from Mendeley

### ISSUE THREAD

**Issue by dnoesgaard** [gbif/content-crawler#35]
In an attempt to categorize literature by taxon, I've started tagging papers using `gbifTaxon:<taxonKey>`, e.g., b688f91b-8f9f-39e4-a378-6d9375247da8: 

```
"tags": [
"2021",
"Agronomy and Crop Science",
"GBIF_cited",
"HU",
"Horticulture",
"Plant Science",
"Species_distributions",
"citation_type:generic",
"gbifTaxon:7202218",
"open_access:true",
"peer_review:true"
]
```

If we could make the crawler add this as field to the ES index, we could start featuring literature on species pages, etc.

```
"gbifTaxonKey": [
"7202218"
]
```

(@MortenHofft, you might also have thoughts on this)

**Comment by MortenHofft** [comment]
It makes sense to me. It would also make it more clear what to do with those citations of species pages.

I would like to add `gbifOccurrenceKey: []` as well. For those cases where someone cites a few individual occurrences (for example a taxonomic treatment). If I understand correctly, then we currently only count those on dataset level. Counting on dataset level makes perfect sense for large downloads, but when a paper cites a few individual occurrences, then it would be nice to capture that as the occurrence probably plays a larger role.

**Comment by dnoesgaard** [comment]
I've added `gbifOccurrence` tags for a few papers now:

91710ee8-d590-3953-a6e9-4cfdc608e5da
51974777-846f-335a-8d6a-687d85a5714e
24412bdf-599e-3c60-ae9d-1d72d557772c
f9ef5a36-cbd8-3a76-a0f9-3d3262070969

`gbifTaxon` has already been applied to ~1,500 papers

**Comment by dnoesgaard** [comment]
(for my own sake, here's how easily pull these from ES using wildcards)

```
% curl --location --request GET 'cms-search.gbif.org:9200/_search' \
--header 'Content-type: application/json' \
--data-raw '{
  "query": {
    "bool": {
      "must": [
        {
          "query_string": {
            "query": "gbifOccurrence*",
            "fields": [
              "tags"
            ]
          }
        }
      ]
    }
  }
}'
```

**Comment by MortenHofft** [comment]
When indexing the taxonKeys I suggest we also resolve the higher ranks and add those. That would make it possible to search for all papers about e.g. a family (and not just papers about specific species).

```
taxonKey: [456,789],
higherRanks: [456,789,1,2,3,4,5,6,10,11,12,13,14,15,16] //including the leaf for convinence i suppose (similar to occ index). So higher ranks probably isn't the best name
```

**Comment by dnoesgaard** [comment]
For citation_type, I believe it could be controlled using

- DOI
- generic
- generic_DOIs_provided

(the latter being when a paper doesn't cite a DOI but provides one when contacted)
