### ISSUE TITLE
literature search by network

### ISSUE THREAD

**Issue by frafra** [gbif/content-crawler#46]
Hi,
it is possible to search literature documents by publisher, but not by network. Would it be possible to add such a filter?

**Comment by MortenHofft** [comment]
For context: several of the hosted portals are scoped by network. Searching literature with a filter for hundreds of datasetKeys are not ideal. If we instead could add the networkKeys then this would be possible. My naive guess is that it wouldn't influence index size much as the number of networks we have is small (10 networks currently).

**Comment by fmendezh** [comment]
gbifNetworkKey  filter and facet are now in production, some examples:
[https://api.gbif.org/v1/literature/search?gbifNetworkKey=379a0de5-f377-4661-9a30-33dd844e7b9a](https://api.gbif.org/v1/literature/search?gbifNetworkKey=379a0de5-f377-4661-9a30-33dd844e7b9a)
[https://api.gbif.org/v1/literature/search?facet=gbifNetworkKey](https://api.gbif.org/v1/literature/search?facet=gbifNetworkKey)
