### ISSUE TITLE
add preview option

### ISSUE THREAD

**Issue by MortenHofft** [gbif/content-crawler#48]
For the website we currently use a mixture of contentful APIs and our own ElasticSearch index.
I would like to only use our own APIs.

**Problem**
We use ES for search. And we use Contentful for displaying individual items (e.g. a data use page).
The reason we still use Contentful instead of just fetching the data from ES is that Contentful supports previews. A preview is the option to view the record in its unpublished state. This is useful for content creators to evaluate their changes before publishing.

And since as ES and Contentful APIs have different data structure we cannot use the same templates to display data. That means that we have to maintain 2 templates or transform data  before using it. It would be nice if we could just use ES for everything. It also adds more points of failure when we depend on multiple APIs.

**Suggestion**
So I'm wondering if it would be much hassle for us to add the preview functionality. It wouldn't have to be for search, but for individual items. The important thing is that it is instant so that the editors workflow is fast and they do not have to wait for the data to be indexed again.

I can use the current index to get individual items by their ID, but what I want as well is to get the unpublished preview data in the same response format. So I imagine an API like `/content/{ID}` and `/content/{ID}?preview=true`. The first will just get the entry from ES. But the second will use the Contentful preview API to get the latest unpublished version and transform it to the same structure as it would look like in ES once published.

Obviously this data mapping service could be made as part of the web layer, but since it already exists in Java it makes sense to reuse that I would think. It also avoids drift over time.

So normally to get the published data one would do
`https://cdn.contentful.com/spaces/SPACE_ID/environments/master/entries?access_token=SECRET`
To get the preview you instead do
`https://preview.contentful.com/spaces/SPACE_ID/environments/master/entries?access_token=OTHER_SECRET`

Notice that the depth of related entries to include can be controlled with the `include=4` parameter

**Comment by fmendezh** [comment]
Currently we don't have any Java based Rest API for content, wouldn't be more or less the same if we index all preview content under a different alias /content_preview/? We can add a new endpoint for all this but I guess it would be for basic read-only operations

**Comment by dnoesgaard** [comment]
Whatever solution is proposed, we would need it to allow instantly previewing draft content. Right now I can preview changes after the ~5 second auto-save interval in the Contentful UI.

**Comment by MortenHofft** [comment]
A search preview sounds like a nice option, but as Daniel says - the most important is "instant" (a few seconds delay is fine) preview of drafts for individual pages. So it cannot rely on indexing everything using the preview API.

**Comment by dnoesgaard** [comment]
Maybe we could build a preview index containing only drafts and perhaps only those updated within the last x days to limit the time it would take to build it?

**Comment by MortenHofft** [comment]
Could work - as long as all the published items that are referenced are also included - whatever their state
