### ISSUE TITLE
Frequent timeouts from Mendeley

### ISSUE THREAD

**Issue by dnoesgaard** [gbif/content-crawler#53]
Crawling of Mendeley often fails, e.g. https://builds.gbif.org/job/run-content-crawler/18751/console:

```
WARN  [2023-03-07 08:46:50,043+0000] [main] org.gbif.content.crawl.mendeley.MendeleyPager: Mendeley returning HTTP[504] with GATEWAY_TIMEOUT
ERROR [2023-03-07 08:46:50,047+0000] [main] org.gbif.content.crawl.mendeley.MendeleyDocumentCrawler: Error crawling Mendeley
```

Rather than give up completely, would it be possible to let the crawler pause for a few seconds and retry the HTTP request when this happens?

**Comment by mike-podolskiy90** [comment]
@dnoesgaard How long should we wait before the next request? How many re-tries needed please?
