### ISSUE TITLE
Mendeley library change - public to private

### ISSUE THREAD

**Issue by dnoesgaard** [gbif/content-crawler#6]
I've noticed that our current Mendeley library is public, which means anyone can add and delete records from it. I've copied the whole thing into a private library instead, and I'd like to test it.

Could we try changing the [groupId](https://github.com/gbif/content-crawler/blob/a87321aed25bb0c1b8301790bf53287acae6e16c/src/main/java/org/gbif/content/crawl/conf/ContentCrawlConfiguration.java#L75) from
dcb8ff61-dbc0-3519-af76-2072f22bc22f

to

e0b4b481-7096-3d64-8cfa-41d5658a931e

on TEST to begin with?

**Comment by fmendezh** [comment]
groupId changed to new test groupId
https://github.com/gbif/gbif-configuration/commit/460115f090f0733aaafcfc80f401813ec3d05f7b

**Comment by dnoesgaard** [comment]
Thanks @fmendezh - for some reason that I can't explain the new group doesn't work:

https://builds.gbif.org/job/run-content-crawler/2399/console
```INFO  [2018-02-02 10:29:44,199+0100] [main] org.gbif.content.crawl.mendeley.MendeleyPager: Requesting data from https://api.mendeley.com/documents?group_id=e0b4b481-7096-3d64-8cfa-41d5658a931e&limit=500&view=all
WARN  [2018-02-02 10:29:44,431+0100] [main] org.gbif.content.crawl.mendeley.MendeleyPager: Mendeley returning HTTP[403] with Forbidden
ERROR [2018-02-02 10:29:44,436+0100] [main] org.gbif.content.crawl.mendeley.MendeleyDocumentCrawler: Error crawling Mendeley
java.lang.RuntimeException: Error communicating with Mendeley API
```
I can access both groups fine manually using the access token:

https://api.mendeley.com/documents?group_id=dcb8ff61-dbc0-3519-af76-2072f22bc22f&limit=500&view=all&access_token=(removed)
https://api.mendeley.com/documents?group_id=e0b4b481-7096-3d64-8cfa-41d5658a931e&limit=500&view=alll&access_token=(removed)

Any idea what might be the problem?
