### ISSUE TITLE
Mendeley crawls failing

### ISSUE THREAD

**Issue by dnoesgaard** [gbif/content-crawler#7]
I've just had four consecutive crawls of Mendeley fail, e.g.

https://builds.gbif.org/job/run-content-crawler/3090/console

Any idea?

**Comment by dnoesgaard** [comment]
@fmendezh, I noticed you initiated a crawl, too. Any idea why it might be failing?

**Comment by dnoesgaard** [comment]
Still failing, same error, it appears. Haven't been able to crawl Mendeley for more than a week now.

**Comment by MortenHofft** [comment]
My guess it that due to the GDPR changes that account that use the API need to accept the new terms.
> Please note that you will not be able to use the Mendeley APIs after 9 May 2018 if you do not accept the Terms and Conditions.

**Comment by dnoesgaard** [comment]
@MortenHofft - did you comment and delete it?

**Comment by MortenHofft** [comment]
Yes I noticed that my comment was useless as Fede had written on skype that he had already done that. Didn't want to add confusion with daft ideas.

**Comment by dnoesgaard** [comment]
@fmendezh - 17 days since I reported this and I'm still unable to crawl Mendeley...
